/**
 * Export Utility Functions
 * Handles exporting scan reports in various formats
 */

interface VulnerabilityFinding {
  line: number;
  type: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  message: string;
  cwe?: string;
  owasp?: string;
  confidence?: number;
  code_snippet?: string;
}

interface ScanReport {
  scan_id: string;
  filename: string;
  language: string;
  timestamp: string;
  scan_time_ms: number;
  findings: VulnerabilityFinding[];
  summary: {
    total: number;
    critical: number;
    high: number;
    medium: number;
    low: number;
  };
}

/**
 * Export report as JSON
 */
export function exportAsJSON(report: ScanReport, filename?: string): void {
  const json = JSON.stringify(report, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  downloadBlob(blob, filename || `scan-report-${report.scan_id}.json`);
}

/**
 * Export report as CSV
 */
export function exportAsCSV(report: ScanReport, filename?: string): void {
  const headers = ['Line', 'Type', 'Severity', 'Message', 'CWE', 'OWASP', 'Confidence'];
  const rows = report.findings.map((f) => [
    f.line,
    f.type,
    f.severity,
    `"${f.message.replace(/"/g, '""')}"`, // Escape quotes
    f.cwe || '',
    f.owasp || '',
    f.confidence || '',
  ]);

  const csv = [
    headers.join(','),
    ...rows.map((row) => row.join(',')),
  ].join('\n');

  const blob = new Blob([csv], { type: 'text/csv' });
  downloadBlob(blob, filename || `scan-report-${report.scan_id}.csv`);
}

/**
 * Export report as Markdown
 */
export function exportAsMarkdown(report: ScanReport, filename?: string): void {
  const md = `# Vulnerability Scan Report

**Scan ID:** ${report.scan_id}  
**File:** ${report.filename}  
**Language:** ${report.language}  
**Date:** ${new Date(report.timestamp).toLocaleString()}  
**Scan Time:** ${report.scan_time_ms}ms

## Summary

- **Total Findings:** ${report.summary.total}
- 🔴 **Critical:** ${report.summary.critical}
- 🟠 **High:** ${report.summary.high}
- 🟡 **Medium:** ${report.summary.medium}
- 🟢 **Low:** ${report.summary.low}

## Vulnerabilities

${report.findings
  .map(
    (f, i) => `### ${i + 1}. ${f.type} (${f.severity.toUpperCase()})

**Line:** ${f.line}  
**Message:** ${f.message}  
${f.cwe ? `**CWE:** ${f.cwe}  ` : ''}${f.owasp ? `**OWASP:** ${f.owasp}  ` : ''}${f.confidence ? `**Confidence:** ${(f.confidence * 100).toFixed(1)}%  ` : ''}

${f.code_snippet ? '```\n' + f.code_snippet + '\n```\n' : ''}`
  )
  .join('\n\n')}

---
*Generated by VulnScanner - AI-based Vulnerability Detection*
`;

  const blob = new Blob([md], { type: 'text/markdown' });
  downloadBlob(blob, filename || `scan-report-${report.scan_id}.md`);
}

/**
 * Export report as HTML
 */
export function exportAsHTML(report: ScanReport, filename?: string): void {
  const severityColors = {
    critical: '#dc2626',
    high: '#ea580c',
    medium: '#f59e0b',
    low: '#10b981',
  };

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vulnerability Scan Report - ${report.filename}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      background: #f8fafc;
      padding: 2rem;
    }
    .container { max-width: 1200px; margin: 0 auto; background: white; padding: 2rem; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
    h1 { font-size: 2rem; margin-bottom: 1rem; color: #0f172a; }
    .meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 2rem 0; }
    .meta-item { padding: 1rem; background: #f1f5f9; border-radius: 8px; }
    .meta-item strong { display: block; font-size: 0.875rem; color: #64748b; margin-bottom: 0.25rem; }
    .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 1rem; margin: 2rem 0; }
    .stat { padding: 1rem; text-align: center; border-radius: 8px; background: #f8fafc; border: 1px solid #e2e8f0; }
    .stat-value { font-size: 2rem; font-weight: bold; }
    .stat-label { font-size: 0.875rem; color: #64748b; margin-top: 0.25rem; }
    .findings { margin-top: 2rem; }
    .finding { margin-bottom: 1.5rem; padding: 1.5rem; border-radius: 8px; border-left: 4px solid; }
    .finding-header { display: flex; justify-content: space-between; align-items: start; margin-bottom: 1rem; }
    .finding-title { font-size: 1.25rem; font-weight: 600; }
    .severity-badge { padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; color: white; text-transform: uppercase; }
    .finding-details { font-size: 0.875rem; color: #475569; margin-bottom: 0.5rem; }
    .code-snippet { background: #1e293b; color: #e2e8f0; padding: 1rem; border-radius: 6px; overflow-x: auto; font-family: 'Courier New', monospace; font-size: 0.875rem; margin-top: 0.5rem; }
    .footer { margin-top: 3rem; padding-top: 2rem; border-top: 1px solid #e2e8f0; text-align: center; color: #64748b; font-size: 0.875rem; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🛡️ Vulnerability Scan Report</h1>
    
    <div class="meta">
      <div class="meta-item">
        <strong>Scan ID</strong>
        <div>${report.scan_id}</div>
      </div>
      <div class="meta-item">
        <strong>File</strong>
        <div>${report.filename}</div>
      </div>
      <div class="meta-item">
        <strong>Language</strong>
        <div>${report.language}</div>
      </div>
      <div class="meta-item">
        <strong>Scan Time</strong>
        <div>${report.scan_time_ms}ms</div>
      </div>
      <div class="meta-item">
        <strong>Date</strong>
        <div>${new Date(report.timestamp).toLocaleString()}</div>
      </div>
    </div>

    <h2>Summary</h2>
    <div class="summary">
      <div class="stat">
        <div class="stat-value">${report.summary.total}</div>
        <div class="stat-label">Total Findings</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color: ${severityColors.critical}">${report.summary.critical}</div>
        <div class="stat-label">Critical</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color: ${severityColors.high}">${report.summary.high}</div>
        <div class="stat-label">High</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color: ${severityColors.medium}">${report.summary.medium}</div>
        <div class="stat-label">Medium</div>
      </div>
      <div class="stat">
        <div class="stat-value" style="color: ${severityColors.low}">${report.summary.low}</div>
        <div class="stat-label">Low</div>
      </div>
    </div>

    <h2>Findings</h2>
    <div class="findings">
      ${report.findings
        .map(
          (f, i) => `
        <div class="finding" style="border-left-color: ${severityColors[f.severity]}; background: ${severityColors[f.severity]}10">
          <div class="finding-header">
            <div class="finding-title">${i + 1}. ${f.type}</div>
            <span class="severity-badge" style="background: ${severityColors[f.severity]}">${f.severity}</span>
          </div>
          <div class="finding-details">
            <strong>Line ${f.line}</strong> • ${f.message}
            ${f.cwe ? `<br><strong>CWE:</strong> ${f.cwe}` : ''}
            ${f.owasp ? ` • <strong>OWASP:</strong> ${f.owasp}` : ''}
            ${f.confidence ? ` • <strong>Confidence:</strong> ${(f.confidence * 100).toFixed(1)}%` : ''}
          </div>
          ${f.code_snippet ? `<pre class="code-snippet"><code>${f.code_snippet.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</code></pre>` : ''}
        </div>
      `
        )
        .join('')}
    </div>

    <div class="footer">
      Generated by <strong>VulnScanner</strong> - AI-based Vulnerability Detection System
    </div>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  downloadBlob(blob, filename || `scan-report-${report.scan_id}.html`);
}

/**
 * Export report as PDF (using browser print)
 */
export function exportAsPDF(report: ScanReport): void {
  // Generate HTML content
  exportAsHTML(report, 'temp-report.html');
  
  // Note: For true PDF generation, consider using a library like jsPDF or pdfmake
  // For now, we'll use the browser's print dialog
  setTimeout(() => {
    window.print();
  }, 500);
}

/**
 * Helper: Download blob as file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Get export format options
 */
export const exportFormats = [
  { value: 'json', label: 'JSON', icon: '📄', description: 'Machine-readable format' },
  { value: 'csv', label: 'CSV', icon: '📊', description: 'Spreadsheet format' },
  { value: 'html', label: 'HTML', icon: '🌐', description: 'Web page format' },
  { value: 'md', label: 'Markdown', icon: '📝', description: 'Documentation format' },
] as const;

export type ExportFormat = typeof exportFormats[number]['value'];

/**
 * Export report in specified format
 */
export function exportReport(report: ScanReport, format: ExportFormat): void {
  switch (format) {
    case 'json':
      exportAsJSON(report);
      break;
    case 'csv':
      exportAsCSV(report);
      break;
    case 'html':
      exportAsHTML(report);
      break;
    case 'md':
      exportAsMarkdown(report);
      break;
    default:
      console.error('Unknown export format:', format);
  }
}
